In [1]:
person={
    'name' : 'prajwal s',
    'sex' : 'male',
    'age' : 20,
    'profession' : 'student'
}

In [2]:
type(person)

dict

In [3]:
person['name']

'prajwal s'

In [4]:
person

{'name': 'prajwal s', 'sex': 'male', 'age': 20, 'profession': 'student'}

In [5]:
person['address']='bangalore'

In [6]:
person


{'name': 'prajwal s',
 'sex': 'male',
 'age': 20,
 'profession': 'student',
 'address': 'bangalore'}

In [7]:
person.pop('age')

20

In [8]:
person


{'name': 'prajwal s',
 'sex': 'male',
 'profession': 'student',
 'address': 'bangalore'}

In [9]:
person.keys()

dict_keys(['name', 'sex', 'profession', 'address'])

In [10]:
person.items()

dict_items([('name', 'prajwal s'), ('sex', 'male'), ('profession', 'student'), ('address', 'bangalore')])

In [11]:
person.values()

dict_values(['prajwal s', 'male', 'student', 'bangalore'])

In [12]:
print(1, 2, 3, sep=' < ')

1 < 2 < 3


In [14]:
import numpy as np

In [15]:
my_lst =[1,2,3,4,5]

In [16]:
arr = np.array(my_lst)
arr

array([1, 2, 3, 4, 5])

In [17]:
arr.shape

(5,)

In [18]:
## multinested array

lst = [1,2,3,4,5]
lst1 = [2,3,4,5,6]
lst2 = [4,5,6,7,8]

arr1 = np.array([lst, lst1, lst2])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [19]:
arr1.shape

(3, 5)

In [20]:
arr =np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr[0:4]

array([1, 2, 3, 4])

In [22]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [23]:
arr1[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [24]:
arr1[1:,3:]

array([[5, 6],
       [7, 8]])

In [28]:
arr1.shape

(3, 5)

In [46]:
arr1[1:3,1:3]

array([[3, 4],
       [5, 6]])

In [47]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [48]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
arr[3:5]=1000

In [50]:
arr


array([   1,    2,    3, 1000, 1000,    6,    7,    8])

In [54]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [55]:
np.random.rand(3,3)

array([[0.98067117, 0.40565886, 0.76735341],
       [0.66465122, 0.78679159, 0.25094393],
       [0.98547969, 0.90068455, 0.3742401 ]])

In [65]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [66]:
arr1[1:3,1:3]

array([[3, 4],
       [5, 6]])